user:
  name:
    maximum: 50
  email:
    maximum: 255
  phone:
    maximum: 20
  password:
    minimum: 6

sessions:
  remember: 1

static_pages:
  limitation:
    maximum: 10
    
users_helper:
  size: 80

users:
  index:
    avatar:
      size: 50
      
show_limit:
  show_1: 1
  show_5: 5
  show_10: 10
  show_15: 15
  show_20: 20
  show_30: 30
  show_50: 50
